### ISSUE TITLE
install does not 

### ISSUE THREAD

**Issue by mxsichael** [bitsy-ai/printnanny-os#13]
I try to install printnanny OS for the first time  I follow the install guide but when I want to link it is takes me to this page and then nothing happens.
![image](https://user-images.githubusercontent.com/33620866/168843002-d140b199-3d93-4399-84a3-011342e3889b.png)

**Comment by leigh-johnson** [comment]
Hey @mxsichael! Can you try out [v0.2.0 Beryl Kirkstone](https://github.com/bitsy-ai/printnanny-os/releases) and let me know how it goes? Follow the instructions in [docs/INSTALL.md](https://github.com/bitsy-ai/printnanny-os/blob/main/docs/INSTALL.MD) to get started.

The welcome web page you were stuck on has been removed entirely in this release and replaced by a splash screen. 
![PXL_20220623_233503018](https://user-images.githubusercontent.com/2601819/178120857-575c1797-97f3-405e-835c-4d8f11dd834f.jpg)
