### ISSUE TITLE
necesito el sofwer  para camaras srihome

### ISSUE THREAD

**Issue by sanpro2134xd** [bitsy-ai/printnanny-os#326]
**Describe your Request**

**Provide Examples**
Does an example of your request exist today? Link to the source of your inspiration. 

**Screenshots or Mockups**

**Comment by leigh-johnson** [comment]
Lo siento, pero no tengo cameras srihome y no conozco para que sirve. Tambien no hablo espanol muy bien. Si quieres contribuir, por favor describa una lista de requisitos. Entonces, puedo ayudarse a descubrir como construir.
